### ISSUE TITLE
Error Handling?

### ISSUE THREAD

**Issue by naamanu** [SydDaps/easy_exports#1]
Currently, looking at some of the methods, not sure error handling works, such as invalid data format and CSV conversion.

**Comment by SydDaps** [comment]
Thank you for reviewing the code, and I appreciate your feedback on the error-handling aspect. I'd like to provide further context and assurance regarding the validity of the data processed by the methods under consideration.
The methods you've mentioned are private methods that are exclusively used within the main method, which can be found here: [generate_exports](https://github.com/SydDaps/easy_exports/blob/f6bf1c3474b8637e70d9e55cbf8d5f63502a374e/lib/easy_exports/exports_generable.rb#L13). This design ensures that the data passed to these private methods is already validated and reliable.
Within the main method, a two-step validation process is implemented to ensure the integrity of the incoming argument. First, I validate the argument using[validate_exclude_exportable_attributes_argument](https://github.com/SydDaps/easy_exports/blob/f6bf1c3474b8637e70d9e55cbf8d5f63502a374e/lib/easy_exports/exclude_exportable_attributes_configurations.rb#L39C7-L39C10). This ensures that the argument is a hash and that each key-value pair consists of either a string or a symbol.
Subsequently, a second validation is performed to confirm that the argument provided for generating exports contains keys that correspond to associations and that their respective values are valid attributes for those associations. This process is detailed here:[validate_association_attributes](https://github.com/SydDaps/easy_exports/blob/f6bf1c3474b8637e70d9e55cbf8d5f63502a374e/lib/easy_exports/exclude_exportable_attributes_configurations.rb#L21C15-L21C15). In case any of these validations fail, the appropriate argument errors are raised.
Rest assured that the private methods invoked within the main method will always receive data with valid attributes due to the validations in place.
